### ISSUE TITLE
Oc is unstable

### ISSUE THREAD

**Issue by anupritaisno1** [benschhold/android_kernel_oneplus_msm8994_custom#2]
I've tried the overclocking feature and the phone freezes and then the phone screen shuts down and the device goes into a screen-off death. I have to force it to reboot by long pressing the power button

**Comment by xdevs23** [comment]
Confirmed.

**Comment by benschhold** [comment]
then your chip quality is not good and you cant oc to max, live with it

Am 24.09.2016 8:52 vorm. schrieb "Simao Gomes Viana" <
notifications@github.com>:

**Comment by xdevs23** [comment]
Lol

Am 24.09.2016 9:06 vorm. schrieb "Benjamin" <notifications@github.com>:

**Comment by anupritaisno1** [comment]
@benschhold it's not just me. I can make this issue happen reliably on any op2 and also I've got proof from more than 5 people that this bug is present

**Comment by xdevs23** [comment]
This bug really exists.

**Comment by xdevs23** [comment]
Does not happen many times for me, because I have some lower hotplug settings etc. to save some battery and still keeping OC, but it happens sometimes, especially when updating many apps from play store...
